### ISSUE TITLE
Ajax 요청을 통한 로그인/회원가입/활승 요청 구현

### ISSUE THREAD

**Issue by Powering111** [jhgim1117/online-activity-accept-website#5]
Ajax 비동기 요청을 이용.

[이 링크](https://github.com/Powering111/ElectronicActivityAcknowledgement)를 참조하세요.

**Comment by jhgim1117** [comment]
kndl.kr의 업데이트와 함께 로그인, 회원가입 등은 kndl.kr의 업데이트 방식에 따라 fetch api를 사용할 예정(개발 중)입니다.
